DROP TABLE ACCOUNT_EBILLER;

DROP TABLE ACCOUNT_ACCOUNT_OWNER;

DROP TABLE EBILL;

DROP TABLE EBILLER;

DROP TABLE ACCOUNT_OWNER;

DROP TABLE PHYSICAL_ACCOUNT_TRANSACTION;

DROP TABLE ELECTRONIC_ACCOUNT_TRANSACTION;

DROP TABLE ACCOUNT_TRANSACTION;

DROP TABLE ACCOUNT;

DROP TABLE HIBERNATE_UNIQUE_KEY;

DROP TABLE ARCHIVED_ACCOUNT;